
INSERT INTO features_toggle (key, name, enabled, description) VALUES
('ai_chat_enabled', 'Xat amb IA', 1, 'Assistència intel·ligent amb Perplexity AI'),
('notifications_enabled', 'Centre de Notificacions', 1, 'Sistema de notificacions en temps real'),
('achievements_enabled', 'Sistema d''Assoliments', 1, 'Punts i premis per activitat'),
('celebrations_enabled', 'Celebracions', 1, 'Animacions de celebració per esdeveniments'),
('premium_unlock_enabled', 'Desbloqueig Premium', 1, 'Sistema de recompenses premium'),
('offline_indicator_enabled', 'Indicador Offline', 1, 'Avís quan no hi ha connexió'),
('reviews_enabled', 'Sistema de Valoracions', 1, 'Valoracions i comentaris de serveis'),
('assessment_enabled', 'Avaluació Personal', 1, 'Questionari i recomanacions personalitzades'),
('dynamic_pricing_enabled', 'Preus Dinàmics', 1, 'Calculadora de preus intel·ligent'),
('admin_panel_enabled', 'Panell Administració', 1, 'Accés al panell d''administració'),
('therapist_dashboard_enabled', 'Dashboard Terapeuta', 1, 'Panell específic per terapeutes'),
('profile_management_enabled', 'Gestió de Perfil', 1, 'Edició de perfil d''usuari'),
('dashboard_stats_enabled', 'Estadístiques Dashboard', 1, 'Mètriques i gràfics al dashboard'),
('payment_plans_enabled', 'Plans de Pagament', 1, 'Ofertes i paquets de sessions'),
('promotions_enabled', 'Sistema de Promocions', 1, 'Descomptes i ofertes especials'),
('session_reflections_enabled', 'Reflexions de Sessió', 1, 'Comentaris post-sessió'),
('pricing_calendar_enabled', 'Calendari de Preus', 1, 'Vista de calendari amb preus'),
('service_categories_enabled', 'Categories de Serveis', 1, 'Organització per categories'),
('revisio_360_enabled', 'Servei Revisió 360°', 1, 'Servei exclusiu premium'),
('vip_page_enabled', 'Pàgina VIP', 1, 'Accés a serveis VIP ultra-exclusius'),
('hero_section_enabled', 'Secció Hero', 1, 'Secció principal de la pàgina d''inici'),
('service_overview_enabled', 'Resum de Serveis', 1, 'Presentació dels serveis principals'),
('pricing_section_enabled', 'Secció de Preus', 1, 'Mostrar preus i tarifes'),
('success_stories_enabled', 'Històries d''Èxit', 1, 'Testimonis de clients'),
('quick_actions_enabled', 'Accions Ràpides', 1, 'Botons d''acció ràpida al dashboard'),
('footer_enabled', 'Peu de Pàgina', 1, 'Informació de contacte i enllaços'),
('mobile_menu_enabled', 'Menú Mòbil', 1, 'Navegació per dispositius mòbils')
ON CONFLICT(key) DO NOTHING;
